### PR TITLE
Implement /ignoretp <name>

### PR DESCRIPTION
**Pull request by SooStrator1136**
See https://discord.com/channels/895546064260718622/895547863571005451/1125395947610968125

### CODE REVIEW

**Comment by Gentleman2292** [comment]
MANNNNNNNN YOU STOLE MY SUGGESTION AND NOW YOU STOLE MY TASK OF CODING IT

😡

**Comment by nothub** [comment]
I changed the command label to `tpi`/`tpignore` so its more uniform with the other labels.

**Comment by nothub** [comment]
I would like to implement the following changes before merge:
- [x] Only keep references to players `UUID` instead of the `Player` object
- [x] Persisting ignored `UUID`'s to disk (file with maximum number of entries per player)

**Comment by Gentleman2292** [comment]
How about
Syncing ignores from /ignore with tpa ignores

**Comment by nothub** [comment]
> How about Syncing ignores from /ignore with tpa ignores

I am not sure how the server implements the `/ignore` command, it is not part of this plugin.
This plugin is used on other servers too, so I want to keep it general to be useable by anyone.

However I can make the path used to store the ignore files configurable so it is easy to integrate with other logic.

**Comment by Gentleman2292** [comment]
> > How about Syncing ignores from /ignore with tpa ignores
> 
> I am not sure how the server implements the `/ignore` command, it is not part of this plugin. This plugin is used on other servers too, so I want to keep it general to be useable by anyone.
> 
> However I can make the path used to store the ignore files configurable so it is easy to integrate with other logic.

Alright i opened an issue on the /ignore plugin that 0b0t uses

**Comment by nothub** [comment]
I gonna merge this, add @SooStrator1136 as editor to this repo, convert `master` to a development branch and create a new `main` branch.

**Pull request merged**
